enum BuildingsEnum {
    LIVING_MODULE = 'LIVING_MODULE',
    STORAGE = 'STORAGE',
    WORKERS_MODULE = 'WORKERS_MODULE',
    FARM_MODULE = 'FARM_MODULE',
    ENERGY_MODULE = 'ENERGY_MODULE',
    MAINTAIN_MODULE = 'MAINTAIN_MODULE',
    THERMOREGULATION_MODULE = 'THERMOREGULATION_MODULE',
    RADIATION_CLEANER_MODULE = 'RADIATION_CLEANER_MODULE',
    TOXICITY_CLEANER_MODULE = 'TOXICITY_CLEANER_MODULE',
    CENTRAL_MODULE = 'CENTRAL_MODULE',
    COMMUNICATION_MODULE = 'COMMUNICATION_MODULE',
    WATER_FLOAT_MODULE = 'WATER_FLOAT_MODULE',
    LOW_ORBIT_ENGINE_MODULE = 'LOW_ORBIT_ENGINE_MODULE'
}

export default BuildingsEnum