enum BuildingsEnum {
    ORE_MINE = 'ORE_MINE',
    REFINER = 'REFINER',
    LIVING_MODULE = 'LIVING_MODULE',
    STORAGE = 'STORAGE',
    WORKERS_MODULE = 'WORKERS_MODULE',
    ASSEMBLY_MODULE = 'ASSEMBLY_MODULE',
    FARM_MODULE = 'FARM_MODULE',
    TRADING_MODULE = 'TRADING_MODULE',
    TELEPORT_MODULE = 'TELEPORT_MODULE',
    EXPEDITIONS_MODULE = 'EXPEDITIONS_MODULE',
    ENERGY_MODULE = 'ENERGY_MODULE',
    MAINTAIN_MODULE = 'MAINTAIN_MODULE'
}

export default BuildingsEnum